### ISSUE TITLE
如何判断当天是否有课

### ISSUE THREAD

**Issue by githubxc** [zfman/TimetableView#1]
如题，如果有课是哪几节课？这个有方法或者接口吗？或者给点思路

**Comment by zfman** [comment]
### 获取当天有课的课程

为此，发布了版本v1.0.1，注意：只更新了android studio的版本，eclipse的版本暂不维护

使用方法如下：

`compile 'com.zhuangfei:TimetableView:1.0.1'`

在SubjectUtils中新增了三个方法

| order       | return       | method           | meaning           |
| :-------------:| :-------------|:-------------| :-------------|
|1 |List<SubjectBean>[] | getSubjectInitial(List<SubjectBean> dataSource) | 获取到一周的所有课程，它是一个长度为7的数组，每个元素是一个集合，分别对应着周一-周日的所有课程|
|1 |List<SubjectBean>[] | getSubjectInitial(List<SubjectBean> dataSource) | 获取到一周的所有课程，它是一个长度为7的数组，每个元素是一个集合，分别对应着周一-周日的所有课程|
|2 |List<SubjectBean> | getTodaySubjects(List<SubjectBean> subjectBeans,int curWeek,int day) | 获取到指定day的有课的课程，返回一个集合。subjectBeans是数据源，curWeek是当前周，day是指星期，0为星期一。。6为周日|
|3 |List<SubjectBean> | getTodayAllSubjects(List<SubjectBean> subjectBeans,int day) | 获取到指定day的所有课程，返回一个集合。subjectBeans是数据源，day是指星期，0为星期一。。6为周日|

### 使用例子
```java
//显示周一课程
    protected void showTodaySubjects() {
        //0表示周一，依次类推，6代表周日
        List<SubjectBean> beans = SubjectUtils.getTodaySubjects(subjectBeans, curWeek, 0);
        String subjectStr=showSubjects(beans);
        Toast.makeText(this, "周一有" + beans.size() + "门课要上\n\n" + subjectStr, Toast.LENGTH_SHORT).show();
    }

    //显示周一所有课程
    protected void showTodayAllSubjects() {
        List<SubjectBean> beans = SubjectUtils.getTodayAllSubjects(subjectBeans, 0);
        String subjectStr=showSubjects(beans);
        Toast.makeText(this, "周一共有" + beans.size() + "门课\n\n" + subjectStr, Toast.LENGTH_SHORT).show();
    }
```
