### ISSUE TITLE
意见征集

### ISSUE THREAD

**Issue by zfman** [zfman/TimetableView#11]
有什么好的建议，可以在下方评论~

**Comment by zfman** [comment]
暂时还没有，不过这个实现也很简单

**Comment by zfman** [comment]
@DaiXiaoshuai 暂时还没有，不过这个想法我会加入到下个版本的计划中

如果你急切需要这个功能的话，可以把项目下载下来，修改module `TimetableView`，然后使你的主项目依赖于你修改后的module即可

至于如何修改，我可以给你一点建议：
如果不需要扩展性的话（也就是说你的项目中周六周日永远都不显示数据），那么直接在`view_content.xml`中将`weekPanel_6`、`weekPanel_7`设为隐藏即可

具体修改位置为：`view_content.xml`
```
<LinearLayout
            android:id="@+id/weekPanel_6"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1.5"
            android:layout_marginBottom="5dp"
            android:orientation="vertical"></LinearLayout>

        <LinearLayout
            android:id="@+id/weekPanel_7"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1.5"
            android:layout_marginBottom="5dp"
            android:orientation="vertical"></LinearLayout>
```

如果需要扩展的话（也就是说，可以设置周六、周日显示与否），那么应该在TimetableView#showView()中根据属性的设置来对这几块布局重新设置宽度，这个宽度需要根据比例计算

如果有问题，可以继续提出..

**Comment by DaiXiaoshuai** [comment]
好的，非常感谢

**Comment by DaiXiaoshuai** [comment]
项目里用了代码混淆，需要在规则里添加这个组件的内容吗

**Comment by zfman** [comment]
@DaiXiaoshuai 不需要添加，这个控件目前还没有混淆

**Comment by DaiXiaoshuai** [comment]
好的，谢谢

**Comment by zfman** [comment]
@DaiXiaoshuai 现在好了，`v2.0.4已发布，`可以参考一下我的实现 [周末显示与隐藏文档](https://github.com/zfman/TimetableView/wiki/%E6%9C%80%E6%96%B0%E6%96%87%E6%A1%A3#%E5%91%A8%E6%9C%AB%E6%98%BE%E7%A4%BA%E4%B8%8E%E9%9A%90%E8%97%8F)

**Comment by AndMy** [comment]
横向的宽度可以控制吗

**Comment by zfman** [comment]
@AndMy 你需要的效果是什么？目前可以设置月份宽度，其他列是平分的

实现其实也是很简单，你只要在`showView()`中控制七列的宽度比例就可以了，你先研究研究

**Comment by zfman** [comment]
@AndMy 
你自己实现时注意修改列的宽度时要同时兼容日期栏旗标布局

**Comment by zfman** [comment]
@AndMy 
升级到`v2.0.6`，因为我发现`v2.0.5`自定义业务逻辑的话会报错，所以这次更新主要是优化自定义。

你的这个需求我给你写了个demo，文档我也写好了，请参见[示例-宽度可设置](https://github.com/zfman/TimetableView/wiki/%E6%9C%80%E6%96%B0%E6%96%87%E6%A1%A3#%E7%A4%BA%E4%BE%8B-%E5%AE%BD%E5%BA%A6%E5%8F%AF%E8%AE%BE%E7%BD%AE)

先看看效果：

<img src="https://raw.githubusercontent.com/zfman/TimetableView/master/images/v2.0.6/img1.jpg" width="50%"/>

有其他问题可以再提出来，需求的话现在已经完全可以自定义了，大部分需求都可以实现，自定义方法可以参考示例，感谢支持。

**Comment by AndMy** [comment]
你好，其实我的意思是如下图
![default](https://user-images.githubusercontent.com/7222340/45278809-50344e00-b501-11e8-8751-c14eb1797ca7.png)

**Comment by zfman** [comment]
目前不会，如果按照你的这个逻辑的话，如果有三个或更多个重叠时怎么办，就没办法把它均分了吧。

现在的课程重叠处理方案和超级课程表的处理方案相同，即：
课程A与B交叉，首先判断是否都在本周有课，如果都有课，那么显示A，然后加个红色的角标来标记有几个重叠的。
如果有一个有课，那么只显示有课的那个，另一个忽略
如果都无课，显示A，B忽略

当然你这个需求可以实现，你可以自定义Operater试试，自定义业务逻辑基本可以实现任何效果

**Comment by AndMy** [comment]
@zfman 哦哦哦，明白了，感谢，太感谢了；有个好的产品很重要。。

**Comment by zfman** [comment]
@AndMy 哈哈，其实你那个实现起来要困难的多，有问题再问我

**Comment by zfman** [comment]
好😊

**Comment by dredreams** [comment]
为什么周一周二周三不能点击的？只能定格在周四？

**Comment by zfman** [comment]
@dredreams 你说的是日期栏吗？那个日期栏高亮默认是当天（今天是周四，所以周四高亮），为什么要点击周二和周三呀？

**Comment by zfman** [comment]
@dredreams 我不是很懂你的需求，课表视图显示的就是一周的课程呀，今天是周五，那么今天的课程在第五列，明天的课程在第六列。如果今天是周日，那么明天的课程可以通过周次切换预览到，参见demo或者文档中的周次切换

**Comment by dredreams** [comment]
抱歉，是我理解错误，谢谢你的解答，正在使用你的项目做一个校园的项目，以后多交流！

**Comment by zfman** [comment]
@dredreams 哈哈，好的没问题

**Comment by SimonZhang115** [comment]
怎样改成英文版，也就是把周一周二这些中文字换成别的

**Comment by gyf-dev** [comment]
希望可以增加设置课程项的gravity，我看你源码设置的是center_horizontal|top，希望增加属性或者方法来修改，比如修改为center

**Comment by zfman** [comment]
@gyf-dev 目前版本是可以设置的

只要监听`OnItemBuildListener`事件就可以了，修改课程项gravity示例：
```java
.callback(new OnItemBuildAdapter(){
                    @Override
                    public void onItemUpdate(FrameLayout layout, TextView textView, TextView countTextView, Schedule schedule, GradientDrawable gd) {
                        super.onItemUpdate(layout, textView, countTextView, schedule, gd);
                        textView.setGravity(Gravity.LEFT);
                    }
                })
```

完整示例：
```java
mTimetableView.source(mySubjects)
                .curWeek(1)
                .curTerm("大三下学期")
                .maxSlideItem(10)
                .callback(new OnItemBuildAdapter(){
                    @Override
                    public void onItemUpdate(FrameLayout layout, TextView textView, TextView countTextView, Schedule schedule, GradientDrawable gd) {
                        super.onItemUpdate(layout, textView, countTextView, schedule, gd);
                        textView.setGravity(Gravity.LEFT);
                    }
                })
                .showView();
```

以上我已经验证通过了

在该监听中可以自定义很多样式，以下是该接口的定义，各个方法参见注释：
```java
/**
     * 课程项构建时回调
     */
    interface OnItemBuildListener {

        /**
         * 构建课程项的文本时回调.
         *
         * @param schedule   该位置对应的课程实体
         * @param isThisWeek 该课程是否是本周上
         * @return
         */
        String getItemText(Schedule schedule, boolean isThisWeek);

        //当changeWeek()调用结束后回调该接口
        //你可以在这里对属性进行二次设置，从而使其符合需求

        /**
         * 课程项构建完成后回调.
         *
         * @param layout        课程项的帧布局
         * @param textView      课程项的内容区域
         * @param countTextView 课程项的角标
         * @param schedule      课程实体
         * @param gd            内容区域的背景是使用GradientDrawable来设置的，你可以二次设置
         */
        void onItemUpdate(FrameLayout layout, TextView textView, TextView countTextView,
                          Schedule schedule, GradientDrawable gd);
    }
```
如果有其他问题，请继续评论，谢谢支持

**Comment by gyf-dev** [comment]
Schedule可以使用setStep增加竖向跨越，能否实现设置横向跨越，比如周一到周五的第一节课都相同，那我就显示一个占据周一到周五的长TextView

**Comment by gyf-dev** [comment]
@zfman 我刚才看了源码，发现是可以这样设置的，所以就把刚才的问题删除了

**Comment by zfman** [comment]
@gyf-dev 要横向跨越的话就只能实现自己的Operator了，模仿SimpleOperator的实现，需要改成相对布局来实现，这个也不难，用相对布局其实会更简单一点，但是空白格子点击的位置就需要计算了

- 用相对布局实现
- 分组、排序后，横向检查数据，如果有可以合并的就合并，创建一个课程项，无非就是将它的宽度设置为多个课程宽度即可，不能合并，走常规操作

**Comment by zfman** [comment]
测试：watch后是否有通知

**Comment by zfman** [comment]
@zfman 测试
