### ISSUE TITLE
课程具体时间

### ISSUE THREAD

**Issue by a645162** [zfman/TimetableView#24]
感觉可以为左边的12345课程节数下添加这节课的时间段。
稍微把这一部分区域的宽度放大一些

**Comment by zfman** [comment]
@a645162 
好的

**Comment by zfman** [comment]
@a645162 
咦，你说的是TimetableView这个控件吗？时间以及宽度都是可以设置的

[侧边栏显示课程时间](https://www.yuque.com/zhuangfei/timetableview/sidebar#spq8xl)

设置侧边栏宽度：
```
// 获取侧边栏宽度px
// @return
.monthWidth()

// 设置侧边栏宽度dp
// @param monthWidthDp
// @return
.monthWidthDp(int monthWidthDp)

// 设置侧边栏宽度px
// @param monthWidthPx
// @return
.monthWidthPx(int monthWidthPx)
```

**Comment by a645162** [comment]
不好意思呀，刚看到这个项目，还没仔细看您给出的文档。

**Comment by zfman** [comment]
@a645162 
哈哈，没事。我还以为你说的是我的怪兽课表项目呢，一看是控件的Issues，属性可以设置的，不过文档比较多
