### ISSUE TITLE
希望加入在添加课表过程中复制课程的功能

### ISSUE THREAD

**Issue by kortin99** [zfman/TimetableView#26]
在添加课程时总会有一周有重复课程的情况，如果能复制之前填入的课程信息不用手打第二遍就好了。还有选周数的时候能滑动多选就舒服了。

**Comment by zfman** [comment]
@LadenxxxxD 
- 复制课程这个功能不属于控件的范畴吧，你可以在实现添加课程页面时做些特殊处理，目前[怪兽课表](http://www.coolapk.com/apk/com.zhuangfei.hputimetable)实现了这个功能，添加或编辑课程的时候可以添加或者编辑多个时间段
- 添加课程-选择周次 也不是控件的功能

嘻嘻，你说的是怪兽课表的功能建议吧？以上

**Comment by zfman** [comment]
所提建议非课表控件范畴，不修复
