### ISSUE TITLE
引入课表导致主题失效

### ISSUE THREAD

**Issue by ldh0423** [zfman/TimetableView#28]
QMUI和课表同时导入会导致QMUI的主题失效
出现问题的QMUI和课表版本分别为2.0.0-alpha02与2.0.7
QMUI在1.4.0版本上不会出现此问题
目前还不清楚是哪个项目导致的问题

**Comment by zfman** [comment]
qmui是什么？课表只是个控件，不会影响到系统的主题的 @ldh0423

**Comment by ldh0423** [comment]
> qmui是什么？课表只是个控件，不会影响到系统的主题的 @ldh0423

实测会的，课表里面有写style，昨晚上我把style删了就解决了
