### ISSUE TITLE
请教一下一个旗标偏移的问题

### ISSUE THREAD

**Issue by UtopiaXC** [zfman/TimetableView#29]
就是下面图片里的这样，越往右列越偏，我以为是我旗标宽度设置的问题，但是看了文档发现旗标宽度改不了，请教一下这个应该怎么处理呢，麻烦了

![00](https://user-images.githubusercontent.com/49057287/70888818-24651980-201c-11ea-8742-fcb66de74ae6.png)

**Comment by zfman** [comment]
@UtopiaXC 你先看下文档，自己实现一个旗标的实现类，参考
https://github.com/zfman/TimetableView/blob/master/AndroidTimetableView/TimetableView/src/com/zhuangfei/timetable/listener/OnSpaceItemClickAdapter.java

创建自己的实现类后设置一下就可以了

**Comment by UtopiaXC** [comment]
> @UtopiaXC 你先看下文档，自己实现一个旗标的实现类，参考
> https://github.com/zfman/TimetableView/blob/master/AndroidTimetableView/TimetableView/src/com/zhuangfei/timetable/listener/OnSpaceItemClickAdapter.java
> 
> 创建自己的实现类后设置一下就可以了

解决了，谢谢

**Comment by zfman** [comment]
@UtopiaXC

你是用什么方法解决的？

其实你这个问题的根本原因是：
1.`TimetableView`控件的宽度你没有充满父级容器
2.我在计算每列宽度是用屏幕宽度算的，并不是用的控件宽度，这是该控件的一个bug，还没来得及修改

你有两种方式解决

- `TimetableView`控件不要设置左右间距，这种方式最简单
- 实现自己的`Operator`

### 实现自己的`Operator`
[AbsOperater.java](https://github.com/zfman/TimetableView/blob/master/AndroidTimetableView/TimetableView/src/com/zhuangfei/timetable/operater/AbsOperater.java)是一个接口，定义了课表如何在界面显示以及刷新，[SimpleOperater.java](https://github.com/zfman/TimetableView/blob/master/AndroidTimetableView/TimetableView/src/com/zhuangfei/timetable/operater/SimpleOperater.java)是默认的实现类

**重写方法**

你需要创建自己的Operator，继承自SimpleOperator，然后重写`getPerWidth()`方法

默认的实现子类中是用屏幕宽度计算每列宽度的，你可以修改为控件的宽度来计算
```java
protected float getPerWidth(){
        float perWidth = 0;
        if(mView.isShowWeekends()){
            perWidth=(ScreenUtils.getWidthInPx(context) -mView.monthWidth())/7;
        }else{
            perWidth=(ScreenUtils.getWidthInPx(context) -mView.monthWidth())/5;
        }
        return perWidth;
    }
```

**设置Operator**

```java
mTimetableView.operator(new MyOperator()).showView();
```

以上方法才是最终的解决方案，我刚看了你的界面发现最后几列的宽度不对，月份列的宽度也不对

**Comment by zfman** [comment]
@UtopiaXC

你可以先确定下是不是左右有间距，图片上看的效果不是那么明显，如果你设置了间距，可以使用上述的最终解决方案

**Comment by UtopiaXC** [comment]
> @UtopiaXC
> 
> 你可以先确定下是不是左右有间距，图片上看的效果不是那么明显，如果你设置了间距，可以使用上述的最终解决方案

谢谢大佬。。刚才吃饭去了没看到回复。
我刚才用你的方法重写了一下左边距的计算方法，发现怎么也对不齐，改成左距离0dp之后发现还是偏，然后我就回去看了framelayout，才想起来这个容器当时为了好看写了边距，我刚才是把边距取消了就解决了。
看了你写的这个Operator我等一下试试。
谢谢了。

**Comment by zfman** [comment]
好的，没事。
