### ISSUE TITLE
动态显示或隐藏非本周课程有 bug

### ISSUE THREAD

**Issue by Robotxm** [zfman/TimetableView#31]
比如设置的当前周是 4，然后手动选择到第 5 周，此时调用`timetable_view.isShowNotCurWeek`和`timetable_view.updateView()`之后，周次选择栏会保持在第 5 周，而下面课表控件显示的课程又会跳回第 4 周的。

**Comment by zfman** [comment]
@Robotxm 
你调用 timetable_view.updateview() 本来就是会跳到当前周呀，这个函数的意思就是刷新界面，当然会用当前周来计算了。

你可以看下demo，切换周次时使课表刷新调用的不是这个方法，参考以下方法（周次选择监听事件）
```java
//设置周次选择属性
        mWeekView.data(schedules)
                .curWeek(curWeek)
                .itemCount(25)
                .callback(new IWeekView.OnWeekItemClickedListener() {
                    @Override
                    public void onWeekClicked(int week) {
                        int cur = mTimetableView.curWeek();
                        tmp = week;
                        //更新切换后的日期，从当前周cur->切换的周week
                        mTimetableView.onDateBuildListener()
                                .onUpdateDate(cur, week);
                        mTimetableView.changeWeekOnly(week);
                    }
                })
              
                .isShow(false)
                .showView();
```

想让周次选择栏恢复调一下weekview.showView()就可以了

**Comment by zfman** [comment]
@Robotxm 
这些文档中以及demo中都有的，你再仔细看看，如果还是不懂的话可以联系qq：1193600556

**Comment by Robotxm** [comment]
那有没有办法做到在当前周是 4，然后切换到了 5，再显示或隐藏非本周课程这一系列操作完成之后保持显示第 5 周的课程而不是跳回第 4 周的课程呢？

**Comment by zfman** [comment]
@Robotxm 
你只要不去调updateView()就不会去重绘课程页面的，单纯的切换周次使用 changeweekOnly()，上述已经给你示例了
demo中调updateView纯粹是为了演示用的，真实用的话只在初始化调一次showView（）

**Comment by zfman** [comment]
@Robotxm 
这个我倒没试过，你可以把第5周设置为当前周再进行操作或者设置完成后你再使用changeWeek切换到刚才到周次也是可以的。为什么要在它不是在当前周的情况下显示隐藏非本周？

**Comment by Robotxm** [comment]
问题解决了，感谢。
